config/routes.rb
Rails.application.routes.draw do

  get 'search/search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'search#search'



  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
   resource  :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] 
    
  scope '(:locale)' do
    resources :books
    
    resources :users do
    member do
      get :following, :followers
    end
    end
    
    resource :user_icons, only: :destroy
    resources :relationships, only: [:create, :destroy]
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy

  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower


  attachment :profile_image

  validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50}

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!
    

    def edit
         @user = User.find(params[:id])
        if @user != current_user
           redirect_to user_path(current_user.id)
        end
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
           flash[:notice] ="You have updated user successfully."
           redirect_to user_path(@user)
        else
           render :edit
        end
    end

    def index
        @user = current_user
        @new_book = Book.new
        @users = User.all
    end

    def show
        @new_book = Book.new
        @user = User.find(params[:id])
        @books = @user.books
    end

    def following
        @user = User.find(params[:id])
        @users = @user.following
    end

    def followers
        @user = User.find(params[:id])
        @users = @user.followers
    end


    private

    def user_params
        params.require(:user).permit(:name, :introduction, :profile_image)
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
 <div><%= hidden_field_tag :followed_id, user.id %></div>
 <%= f.submit "フォローをする",class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
  html: { method: :delete }) do |f| %>
  <%= f.submit "フォローを外す", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
    <%= @user.errors.count %>件のerrorが発生しました
    <% @user.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
<% end %>

<main>
 <div class="container mt-3">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <div class="user_title">
         <h1>User info</h1>
        </div>

       <%= form_with model:@user, local:true do |f| %>
         <div class="name">
          <label for="inputName">Name</label></br>
          <%= f.text_field :name,autofocus: true, id:"inputName", placeholder:"名前", :size => 60 %>
         </div>
         <div class="image">
          <label for="inputImage">image</label></br>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
         </div>
         <div class="introduction">
          <label for="inputIntroduction">Introduction</label></br>
          <%= f.text_area :introduction,id:"Introduction", size: "60x3" %>
         </div>
           <%= f.submit "Update User" %>
       <% end %>
     </div>
    </div>
  </div>
</main>

app/views/users/followers.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-12">
     <main>
         <h1>Follower Users</h1>
         <table cellspacing="15">
             <thead>
                 <tr>
                     <th>image</th><th>name</th><th></th><th></th><th></th>
                 </tr>
             </thead>
             <tbody>
                <% @users.each do |user| %>
                 <tr>
                     <td><%= attachment_image_tag user,:profile_image,:fill,40,40,fallback:"no_image.jpg",size:'40x40' %></td>
                     <td><%= user.name %></td>
                     <td><a>フォロー数：<%= user.following.count %></a></td>
                     <td><a>フォロワー数：<%= user.followers.count %></a></td>
                     <td><%= link_to "Show", user_path(user) %></td>
                 </tr>
                <% end %>
             </tbody>
         </table>
     </main>
   </div>
 </div>
</div>

app/views/users/following.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-12">
     <main>
         <h1>Follow Users</h1>
         <table cellspacing="15">
             <thead>
                 <tr>
                     <th>image</th><th>name</th><th></th><th></th><th></th>
                 </tr>
             </thead>
             <tbody>
                <% @users.each do |user| %>
                 <tr>
                     <td><%= attachment_image_tag user,:profile_image,:fill,40,40,fallback:"no_image.jpg",size:'40x40' %></td>
                     <td><%= user.name %></td>
                     <td><a>フォロー数：<%= user.following.count %></a></td>
                     <td><a>フォロワー数：<%= user.followers.count %></a></td>
                     <td><%= link_to "Show", user_path(user) %></td>
                 </tr>
                <% end %>
             </tbody>
         </table>
     </main>
   </div>
 </div>
</div>

app/views/users/index.html.erb
<div class="main container">
   <div class="side bar row">

   <%= render 'books/list', book: @new_book, user: @user %>

   <div class="main content col-md-8 offset-md-1">
    <h1>Users</h1>
     <table class="table table-hover table-inverse">
            <thead>
               <tr>
                <th>image</th><th>name</th><th colspan="3"></th>
               </tr>
            </thead>
            <tbody>
             <% @users.each do |user| %>
               <tr>
                 <td><%= attachment_image_tag user,:profile_image,:fill,40,40,fallback:"no_image.jpg",size:'40x40' %></td>
                 <td><%= user.name %></td>

                 <td>
                     <p>フォロー数：<%= user.following.count %></p>
                 </td>
                 <td>
                     <p>フォロワー数：<%= user.followers.count %></p>
                 </td>
                 <td>
                    <% if current_user != user %>
                     <p>
                         <% if current_user.following?(user) %>
                           <%= render 'users/unfollow', user: user  %>
                         <% else %>
                           <%= render 'users/follow', user: user %>
                         <% end %>
                     </p>
                     <% end %>
                 </td>

                 <td><%= link_to "Show", user_path(user) %></td>
               </tr>
              <% end %>
            </tbody>
           </table>
   </div>
  </div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
<div class="flash">
<%= flash[:notice] %>
</div>
<% end %>

<div class="main container">
   <div class="side bar row">
    
  

  <%= render 'books/list', book: @new_book, user: @user %>

      <div class="main content col-md-8 offset-md-1">
          <h1 class="Book_contents">Books</h1>
           <table class="table table-hover table-inverse">
            <thead>
               <tr>
                 <th></th><th>Title</th><th>Opinion</th><th colspan="3"></th>
               </tr>
            </thead>
            <tbody>
            　<% @books.each do |book| %>
               <tr>
                 <td>
                    <%= link_to user_path(book.user) do %>
                      <%= attachment_image_tag book.user,:profile_image,:fill,40,40,fallback:"no_image.jpg",size:'40x40' %>
                     <% end %>
                 </td>
                 <td><%= link_to book.title, book_path(book) %></td>
                 <td><%= book.body %></td>
                 </td>
               </tr>
              <% end %>
            </tbody>
           </table>
      </div>

 </div>
</div>