config/routes.rb
Rails.application.routes.draw do

  get 'search/search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'search#search'



  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
   resource  :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] 
    
  scope '(:locale)' do
    resources :books
    
    resources :users do
    member do
      get :following, :followers
    end
    end
    
    resource :user_icons, only: :destroy
    resources :relationships, only: [:create, :destroy]
    end

end

app/models/book.rb
class Book < ApplicationRecord
    
    belongs_to :user
    has_many :book_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    
    validates :title, {presence: true}
    validates :body, {presence: true, length: {maximum: 200}}
    
    
    def favorites_by?(user)
        favorites.where(user_id: user.id).exists?
    end    
    
    def self.search(keyword)
  where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"])
end
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    before_action :ensure_correct_user, only: [:edit,:update]

    def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id
        if @book.save!
         flash[:notice] ="You have created book successfully."
         redirect_to book_path(@book)
        else
         @user = current_user
         @books = Book.all
         render :index
        end
    end

    def index
        @book = Book.new
        @user = current_user
        @books = Book.all
        @book_comments = BookComment.all
    end

    def show
        @new_book = Book.new
        @book = Book.find(params[:id])
        @user = @book.user
        @book_comments = @book.book_comments
        @book_comment = BookComment.new
    end

    def edit
        @book = Book.find(params[:id])
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path
    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
           flash[:notice] ="You have created book successfully."
           redirect_to book_path
        else
           render :edit
        end
    end

    def ensure_correct_user
        @book = Book.find(params[:id])
        if @book.user != current_user
           redirect_to books_path
        end
    end


    private

    def book_params
    params.require(:book).permit(:title, :body)
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
<table>
     <tbody>
      <% book_comments.each do |book_comment| %>
      <tr>
       <td>
        <%= attachment_image_tag book_comment.user,:profile_image,:fill,40,40,fallback:"no_image.jpg",size:'40x40' %></br>
        <%= book_comment.user.name %>
       </td>
       <td>
        <%= book_comment.comment %>
       </td>
       <td>
        <% if book_comment.user == current_user %>
        <div class="btn btn-danger"><%= link_to "Destroy",book_book_comment_path(book, book_comment), {method: :delete,class: "Btn"}%></div>
       </td>
      </tr>
       <% end %>
       <% end %>
     </tbody>
</table>

app/views/books/_like.html.erb
<% if user_signed_in? %>
<% if book.favorites_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book),method: :delete, remote: true do %>
      ♥<%= book.favorites.count %>
      <% end %>
    </p>
      <% else %>
    <p>
      <%= link_to book_favorites_path(book),method: :post, remote: true do %>
      ♡<%= book.favorites.count %>
      <% end %>
    </p>
<% end %>
<% end %>

app/views/books/_list.html.erb
     <div class="col-md-3">
      <h1>User info</h1>
       <div class="profile_image">
        <%= attachment_image_tag user,:profile_image,:fill,60,60,fallback:"no_image.jpg"%>  <!-- @user -> user -->
       </div>
        <table class="table">
            <tr>
                <td>name</td>
                <td><%= user.name %></td>
            </tr>
            <tr>
                <td>introduction</td>
                <td><%= user.introduction %></td>
            </tr>
            <tr>
                <td>follows</td>
                <td>
                    <%= link_to following_user_path(user), method: :get do %>
                    <p><%= user.following.count %></p>
                    <% end %>
                </td>
            </tr>
            <tr>
                <td>followers</td>
                <td>
                    <%= link_to followers_user_path(user), method: :get do %>
                    <%= user.followers.count %>
                    <% end %>
                </td>
            </tr>

        </table>

          <% if current_user == user %>
            <div>
              <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block", method: :get do  %>
               <i class="fas fa-user-cog edit_user_91"></i>
              <% end %>
            </div>
          <% else %>
            <div>
                <p>
                    <% if current_user.following?(user) %>
                    <%= render 'users/unfollow', user: user  %>
                    <% else %>
                    <%= render 'users/follow', user: user %>
                    <% end %>
                </p>
            </div>
          <% end %>

        <div class="New book">
          <h1 class="mt-3">New book</h1>
            <%= form_with model: book, local:true do |f| %> <!-- @book -> book -->
             <div class="book_title">
              <div class="title">Title</div>
              <%= f.text_field :title %>
             </div>
             <div class="book_opinion">
              <div class="opinion">Opinion</div>
              <%= f.text_area :body %><br>
             </div>
              <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
            <% end %>
        </div>
     </div>

app/views/books/_serches.html.erb
<% if user_signed_in? %>
　<%= form_with url: search_path, local: true, method: :get do |f| %>
    <%= f.text_field 'search[value]' %>
    <%= f.select 'search[model]', options_for_select({ "User" => "user", "Book" => "book" }) %>
    <%= f.select 'search[how]', options_for_select({ "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"  }) %>
    <%= f.submit "検索" %>
  <% end %>
 <% end %>

app/views/books/comment.js.erb
$('#comment_<%= @book_comments.ids %>').html("<%= j(render partial: 'books/comment', locals: {book: @book, book_comments: @book_comments} ) %>");

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-lg-5 px-5 mx-auto">
    <h1>Editing Book</h1>

    <%= form_with model: @book,local:true do |f| %>

    <div class="form-group">
      <p>Title</p>
      <%= f.text_field :title, :class => 'text' %>
    </div>
    <div class="form-group">
      <p>Opinion</p>
      <%= f.text_area :body, :class => 'text' %>
    </div>
    <div class="form-group">
      <%= f.submit 'Update Book', :class => 'submit' %>
    </div>
      <% end %>

    <div class="form-group">
      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
    </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="main container">
   <div class="side bar row">

    <%= render 'books/list', book: @book, user: @user %>

    <div class="main content col-md-8 offset-md-1">

     <%= render 'books/serches' %>

    <h1>Books</h1>

    <table class="table table-hover table-inverse">
            <thead>
               <tr>
                <th></th><th>Title</th><th>Opinion</th><th colspan="3"></th>
               </tr>
            </thead>
            <tbody>
            　<% @books.each do |book| %>
               <tr>
                 <td>
                     <%= link_to user_path(book.user.id) do %>
                      <%= attachment_image_tag book.user,:profile_image,:fill,40,40,fallback:"no_image.jpg",size:'40x40' %>
                     <% end %>
                 </td>
                 <td><%= link_to book.title, book_path(book) %></td>
                 <td><%= book.body %></td>
                 </td>
                 <td>
                  <div id="book_<%= book.id %>">
                   <%= render 'books/like', book: book %>
                  </div>
                 </td>
                 <td>
                  <p>
                   コメントの数：
                   <%= book.book_comments.count %>
                  </p>
                 </td>
               </tr>
              <% end %>
            </tbody>
           </table>
    </div>
 </div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
<div class="flash">
<%= flash[:notice] %>
</div>
<% end %>



<div class="main container">
   <div class="side bar row">

    <%= render 'books/list', book: @new_book, user: @user %>

    <div class="main content col-md-8 offset-md-1">

          <h1 class="Book_contents2">Book detail</h1>
           <table class="table table-hover table-inverse">
            <tbody>
               <tr>
                 <td>
                  <%= link_to user_path(@user), method: :get do %>
                   <%= attachment_image_tag @user,:profile_image,:fill,40,40,fallback:"no_image.jpg",size:'40x40' %></br>
                   <%= @user.name %>
                  <% end %>
                 </td>
                 <td><%= @book.title %></a></td>
                 <td><%= @book.body %></td>
                 <td>
                   <div id="book_<%= @book.id %>">
                   <%= render 'books/like', book: @book %>
                  </div>
                 </td>
                 <td>
                   <p>コメント件数:<%= @book_comments.count %>
                   </P>
                 </td>
                 <% if @user.id == current_user.id %>
                  <td>
                   <div class="btn btn-success"><%= link_to "Edit",edit_book_path(@book),{class: "Btn"}%></div>
                  <td>
                   <div class="btn btn-danger"><%= link_to "Destroy",book_path(@book), {method: :delete,class: "Btn"}%></div>
                  </td>
                 <% end %>
               </tr>
            </tbody>
           </table>

           <div class="comments">

            <div id ="comment_<%= @book_comments.ids %>">
             <%= render 'books/comment', book: @book, book_comments: @book_comments %>
            </div>

           </div>

           <div class="new_comment">
            <%= form_with(model:[@book,@book_comment]) do |f| %>
             <%= f.text_area :comment,  size: "90x3"%></br>
             <%= f.submit"送信" %>
            <% end %>
           </div>

      </div>
   </div>
</div>