config/routes.rb
Rails.application.routes.draw do

  get 'search/search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'search#search'



  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
   resource  :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] 
    
  scope '(:locale)' do
    resources :books
    
    resources :users do
    member do
      get :following, :followers
    end
    end
    
    resource :user_icons, only: :destroy
    resources :relationships, only: [:create, :destroy]
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
    belongs_to :user
    has_many :book_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    
    validates :title, {presence: true}
    validates :body, {presence: true, length: {maximum: 200}}
    
    
    def favorites_by?(user)
        favorites.where(user_id: user.id).exists?
    end    
    
    def self.search(keyword)
  where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"])
end
    
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

    belongs_to :user
    belongs_to :book,optional: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
    belongs_to :user
    belongs_to :book
    
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord

    belongs_to :follower, class_name:"User"
    belongs_to :followed, class_name:"User"

    validates :follower_id, presence:true
    validates :followed_id, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy

  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower


  attachment :profile_image

  validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50}

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/bookes_controller.rb
class BookesController < ApplicationController

    def create
    end

    def index
    end

    def show
    end

    def edit
    end

    def destroy
    end
    
    def update
    end

    private
    def book_params
    params.require(:book).permit(:title, :body)
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    before_action :ensure_correct_user, only: [:edit,:update]

    def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id
        if @book.save!
         flash[:notice] ="You have created book successfully."
         redirect_to book_path(@book)
        else
         @user = current_user
         @books = Book.all
         render :index
        end
    end

    def index
        @book = Book.new
        @user = current_user
        @books = Book.all
        @book_comments = BookComment.all
    end

    def show
        @new_book = Book.new
        @book = Book.find(params[:id])
        @user = @book.user
        @book_comments = @book.book_comments
        @book_comment = BookComment.new
    end

    def edit
        @book = Book.find(params[:id])
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path
    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
           flash[:notice] ="You have created book successfully."
           redirect_to book_path
        else
           render :edit
        end
    end

    def ensure_correct_user
        @book = Book.find(params[:id])
        if @book.user != current_user
           redirect_to books_path
        end
    end


    private

    def book_params
    params.require(:book).permit(:title, :body)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
   def top
   end

   def about
   end

end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!
    

    def edit
         @user = User.find(params[:id])
        if @user != current_user
           redirect_to user_path(current_user.id)
        end
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
           flash[:notice] ="You have updated user successfully."
           redirect_to user_path(@user)
        else
           render :edit
        end
    end

    def index
        @user = current_user
        @new_book = Book.new
        @users = User.all
    end

    def show
        @new_book = Book.new
        @user = User.find(params[:id])
        @books = @user.books
    end

    def following
        @user = User.find(params[:id])
        @users = @user.following
    end

    def followers
        @user = User.find(params[:id])
        @users = @user.followers
    end


    private

    def user_params
        params.require(:user).permit(:name, :introduction, :profile_image)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/bookes_helper.rb
module BookesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">

    <script src="https://kit.fontawesome.com/05e7971d55.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body class="d-flex flex-column vh-100">
      <header class="bg-secondary text-white">
       <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
        <%= link_to "Bookers", root_path ,class:"text-white"%>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
         </button>

         <div class="collapse navbar-collapse" id="navbarNavDropdown">
         <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="header">
                 <i class="fas fa-home"></i>
                 <%= link_to "Home", user_path(current_user.id) ,class:"text-white" %>
              </li>

              <li class="header">
                  <i class="fas fa-users"></i>
                  <%= link_to "Users", users_path ,class:"text-white"%>
              </li>

              <li class="header">
                  <i class="fas fa-book-open"></i>
                  <%= link_to "Books", books_path ,class:"text-white"%>
              </li>

              <li class="header">
                 <i class="fas fa-sign-out-alt"></i>
                 <%= link_to "logout", destroy_user_session_path, method: :delete ,class:"text-white" %>
              </li>

            <% else %>

              <li class="header">
                 <i class="fas fa-home"></i>
                 <%= link_to "Home", root_path ,class:"text-white"%>
              </li>

             <li class="header">
                  <i class="fas fa-link"></i>
                  <%= link_to "About", home_about_path ,class:"text-white"%>
             </li>

             <li class="header">
                  <i class="fas fa-user-plus"></i>
                  <%= link_to "sign up", new_user_registration_path ,class:"text-white"%>
             </li>
             <li class="header">
                  <i class="fas fa-sign-in-alt"></i>
                  <%= link_to "login", new_user_session_path ,class:"text-white"%>
             </li>

            <% end %>
        </div>
        </div>
       </nav>
      </header>

      <main>
          
          
          <%= yield %>
          
      </main>
      <footer>
         <div class="mt-5">
          <p class="text-center">CopyRight Infratop.inc</p>
         </div>
      </footer>

    </body>
</html>